#!/usr/bin/env python
# -*- coding:utf-8 -*-


# ############################################################################
#  license :
# ============================================================================
#
#  File :        SynchroMotorDS.py
#
#  Project :     
#
# This file is part of Tango device class.
# 
# Tango is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Tango is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Tango.  If not, see <http://www.gnu.org/licenses/>.
# 
#
#  $Author :      ASSnull$
#
#  $Revision :    $
#
#  $Date :        $
#
#  $HeadUrl :     $
# ============================================================================
#            This file is generated by POGO
#     (Program Obviously used to Generate tango Object)
# ############################################################################

__all__ = ["SynchroMotorDS", "SynchroMotorDSClass", "main"]

__docformat__ = 'restructuredtext'

import PyTango
import sys
# Add additional import
#----- PROTECTED REGION ID(SynchroMotorDS.additionnal_import) ENABLED START -----#
from itertools import groupby
#----- PROTECTED REGION END -----#	//	SynchroMotorDS.additionnal_import

# Device States Description
# No states for this device


class SynchroMotorDS (PyTango.Device_4Impl):
    """"""
    
    # -------- Add you global variables here --------------------------
    #----- PROTECTED REGION ID(SynchroMotorDS.global_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	SynchroMotorDS.global_variables

    def __init__(self, cl, name):
        PyTango.Device_4Impl.__init__(self,cl,name)
        self.debug_stream("In __init__()")
        SynchroMotorDS.init_device(self)
        #----- PROTECTED REGION ID(SynchroMotorDS.__init__) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	SynchroMotorDS.__init__
        
    def delete_device(self):
        self.debug_stream("In delete_device()")
        #----- PROTECTED REGION ID(SynchroMotorDS.delete_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	SynchroMotorDS.delete_device

    def init_device(self):
        self.debug_stream("In init_device()")
        self.get_device_properties(self.get_device_class())
        #----- PROTECTED REGION ID(SynchroMotorDS.init_device) ENABLED START -----#
       
        #----- PROTECTED REGION END -----#	//	SynchroMotorDS.init_device

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")
        #----- PROTECTED REGION ID(SynchroMotorDS.always_executed_hook) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	SynchroMotorDS.always_executed_hook

    # -------------------------------------------------------------------------
    #    SynchroMotorDS read/write attribute methods
    # -------------------------------------------------------------------------
    
    
    
            
    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")
        #----- PROTECTED REGION ID(SynchroMotorDS.read_attr_hardware) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	SynchroMotorDS.read_attr_hardware


    # -------------------------------------------------------------------------
    #    SynchroMotorDS command methods
    # -------------------------------------------------------------------------
    
    def dev_state(self):
        """ This command gets the device state (stored in its device_state data member) and returns it to the caller.
        :return: Device state
        :rtype: PyTango.CmdArgType.DevState
        """
        self.debug_stream("In dev_state()")
        argout = PyTango.DevState.UNKNOWN
        #----- PROTECTED REGION ID(SynchroMotorDS.State) ENABLED START -----#
        argout = PyTango.DevState.ON
        self.set_state(argout)
        #----- PROTECTED REGION END -----#	//	SynchroMotorDS.State
        if argout != PyTango.DevState.ALARM:
            PyTango.Device_4Impl.dev_state(self)
        return self.get_state()
        
    def dev_status(self):
        """ This command gets the device status (stored in its device_status data member) and returns it to the caller.
        :return: Device status
        :rtype: PyTango.ConstDevString
        """
        self.debug_stream("In dev_status()")
        argout = ""
        #----- PROTECTED REGION ID(SynchroMotorDS.Status) ENABLED START -----#
        self.argout = "Status is ON"
        #----- PROTECTED REGION END -----#	//	SynchroMotorDS.Status
        self.set_status(self.argout)
        self.__status = PyTango.Device_4Impl.dev_status(self)
        return self.__status
        
    def Move(self, argin):
        """ 
        :param argin: 
        :type argin: PyTango.DevVarStringArray
        """
        self.debug_stream("In Move()")
        #----- PROTECTED REGION ID(SynchroMotorDS.Move) ENABLED START -----#
        try:
            for i in argin:        
                print "The device is:", i
                dev = PyTango.DeviceProxy(str(i))                 
                list_commands = dev.get_command_list()
                #print list_commands
                if "Move" in list_commands:
                    dev.Move()
                    print "Move the device:", i
                else:
                    print "NO Command: Move in DeviceProxy:", i               
        except:
            print "Error: the input is not valid."
   
        #----- PROTECTED REGION END -----#	//	SynchroMotorDS.Move
        
    def GetPositions(self, argin):
        """ 
        :param argin: 
        :type argin: PyTango.DevVarStringArray
        :rtype: PyTango.DevVarDoubleArray
        """
        self.debug_stream("In GetPositions()")
        argout = [0.0]
        #----- PROTECTED REGION ID(SynchroMotorDS.GetPositions) ENABLED START -----#
        list_positions = []             
        try: 
            for i in argin:
                dev = PyTango.DeviceProxy(str(i)) 
                list_attributes = dev.get_attribute_list()
                #print list_attributes
                if "Position" in list_attributes:
                    pos = dev.Position
                    print "DeviceProxy:", i, "has Position:", pos
                    list_positions.append(pos)
                else:
                    print "NO Attribute: Position in DeviceProxy:", i
             
        except:
            print "Error: the input is not valid."
        return list_positions
        #----- PROTECTED REGION END -----#	//	SynchroMotorDS.GetPositions
        return argout
        
    def GetDevicesStatus(self, argin):
        """ 
        :param argin: 
        :type argin: PyTango.DevVarStringArray
        :rtype: PyTango.DevVarStringArray
        """
        self.debug_stream("In GetDevicesStatus()")
        argout = [""]
        #----- PROTECTED REGION ID(SynchroMotorDS.GetDevicesStatus) ENABLED START -----#
        list_status = []             
        try: 
            for i in argin:
                dev_proxy = PyTango.DeviceProxy(i) 
                list_attributes = dev_proxy.get_attribute_list()
                if "Status" in list_attributes:
                    status = dev_proxy.Status()
                    print status
                    list_status.append(str(status))
                    print list_status
                else:
                    print "NO Attribute: Status in DeviceProxy:", i                 
        except:
            print "Error: the input is not valid."
        argout = list_status 
        return argout    
        #----- PROTECTED REGION END -----#	//	SynchroMotorDS.GetDevicesStatus
        return argout
        

    #----- PROTECTED REGION ID(SynchroMotorDS.programmer_methods) ENABLED START -----#
    
    
  
        
                
    #----- PROTECTED REGION END -----#	//	SynchroMotorDS.programmer_methods

class SynchroMotorDSClass(PyTango.DeviceClass):
    # -------- Add you global class variables here --------------------------
    #----- PROTECTED REGION ID(SynchroMotorDS.global_class_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	SynchroMotorDS.global_class_variables


    #    Class Properties
    class_property_list = {
        }


    #    Device Properties
    device_property_list = {
        }


    #    Command definitions
    cmd_list = {
        'Move':
            [[PyTango.DevVarStringArray, "none"],
            [PyTango.DevVoid, "none"]],
        'GetPositions':
            [[PyTango.DevVarStringArray, "none"],
            [PyTango.DevVarDoubleArray, "none"]],
        'GetDevicesStatus':
            [[PyTango.DevVarStringArray, "none"],
            [PyTango.DevVarStringArray, "none"]],
        }


    #    Attribute definitions
    attr_list = {
        }


def main():
    try:
        py = PyTango.Util(sys.argv)
        py.add_class(SynchroMotorDSClass, SynchroMotorDS, 'SynchroMotorDS')
        #----- PROTECTED REGION ID(SynchroMotorDS.add_classes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	SynchroMotorDS.add_classes

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed as e:
        print ('-------> Received a DevFailed exception:', e)
    except Exception as e:
        print ('-------> An unforeseen exception occured....', e)

if __name__ == '__main__':
    main()
